version: '3'

services:
  smarthire-api-web:
    build: ./images/nginx
    container_name: smarthire-api-web
    depends_on:
      - php
    ports:
      - 5500:80
    networks:
      default:
        aliases:
          - smarthire.local
    volumes:
      #common
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/host.conf:/etc/nginx/conf.d/smarthire.conf
      - ./log/nginx:/var/log/nginx
      #site
      - ../src/public:/var/www/smarthire/public
      - ../src/public/swagger:/var/www/smarthire/public/swagger
      - ../upload:/var/www/smarthire/images

  smarthire-api:
    build: ./images/php
    container_name: smarthire-api
    depends_on:
      - smarthire-db
    environment:
      DB_HOST: smarthire-db
      DB_PORT: 5432
      DB_USER: smarthire
      DB_PASS: secret
      DB_NAME: smarthire
      UPLOAD_DIRECTORY: /var/www/smarthire/images
    volumes:
      - ./log/php:/var/www/smarthire/data/logs
      - ../src/public:/var/www/smarthire/public
      - ../src/config:/var/www/smarthire/config
      - ../src/app:/var/www/smarthire/app
      - ../src/vendor:/var/www/smarthire/vendor
      - ../src/composer.json:/var/www/smarthire/composer.json
      - ../upload:/var/www/smarthire/images

  smarthire-db:
    build: ./images/db
    container_name: smarthire-db
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: smarthire
      POSTGRES_DB: smarthire
    volumes:
      - ./resources/db:/var/lib/postgresql